version: '3'
services:

  postgres-db:
    image: postgres:9.6
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres

  rails-govuk-app:
    build: .
    environment:
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=1234
      - DATABASE_HOST=postgres-db
      - DATABASE_PORT=5432
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - postgres-db